config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :users

  resources :users do
    post "/contact" => "users#contact", as: "contact"
    resources :orders
    resources :msgs
    patch "/orders/:id/archivado" => "orders#archivado", as: "archivado"
    patch "/orders/:id/change_status" => "orders#change_status", as: "change_status"
    patch "/orders/:id/delete" => "orders#delete", as: "delete_order"
    post "/orders/:id/payment" => "orders#payment", as: "payment"
    post "/orders/calcula" => "orders#calcula", as: "calcula"
  end

  get "/logout" => "users#logout", as: "logout"
  post "/login" => "users#login", as: "login"
  patch "/users/:id/inactive" => "users#inactive", as: "inactive"
  

  post "/users/:id/reconfirm" => "users#reconfirm", as: "reconfirm"

  get "/users/:id/index_archivados" => 'users#index_archivados', as: "index_archivados"

  get "verifica/:id", to: "users#email_verification", as: "confirmemail"

  post "/forgot" => "users#forgot_check", as: "forgot_check"
  get "forgot/:id" => "users#forgot_change", as: "forgot_change"
  patch "/forgot/:id/success" => "users#forgot_success", as: "forgot_success"

  

end

app/models/user.rb
class User < ActiveRecord::Base

	validates :name, :gender, :address, presence: true, on: [:create, :update]
	validates :username, presence: true, uniqueness: true, length: { minimum: 5 }, on: [:create, :update]
	validates :email, presence: true, uniqueness: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}, on: [:create, :update]
	validates :password, presence: true, length: { minimum: 6 }, on: [:create, :update]


	has_many :orders
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
		@user = User.find(session[:user])
      	
      	respond_to do |format|
        	format.html
        	format.json {render json: @users if @user.role == 0}
      	end
	end

	def new
	end

	def create
		@user = User.new(user_params)
		@user.role = 2
		@user.status = true

		if @user.save

			@url = request.protocol.to_s + request.host_with_port.to_s  + "/verifica/" + @user.id.to_s
			#UserMailer.email_verification(@user.name, @user.email, @url).deliver
			UserMailer.email_verification(@user.name, @user.email, @url).deliver_now

			#redirect_to @user
			session[:user] = @user.id
			redirect_to @user
		else
			#render "new"
			render "/index"
		end
	end



	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if params[:user][:email] != @user.email
			@url = request.protocol.to_s + request.host_with_port.to_s  + "/verifica/" + @user.id.to_s
			#UserMailer.email_verification(@user.name, @user.email, @url).deliver
			UserMailer.email_verification(@user.name, @user.email, @url).deliver_now
			flash[:notice] = 'Changes Done successfully, Email confirmation has been sent.'
			params[:user][:verified] = false
		end	


		if @user.update(user_params)
			redirect_to @user
			flash[:notice] = 'Changes Done successfully.'
		else
			render "edit"		
		end
	end

	def show
		@actual_date = Time.now
		@user = User.find(params[:id])
		
		if @user.role == 2
			@orders = Order.where(user_id: params[:id]).where.not(status: "deleted")
			@orders_history = Order.where(user_id: params[:id])
			#@orders = Order.where(user_id: params[:id])
		else
			@orders = Order.all.where(archivado: false).where.not(status: "deleted")
			@orders_history = Order.all.where(archivado: false)

		end

		#render "index"
	end

	def login
		user = User.where(username: user_params[:username]).first
		
		if user
			if user.status
				if user.password == user_params[:password]
					session[:user] = user.id
					redirect_to user
				else
					flash[:notice] = 'Invalid User or Password'
					render "/index"
				end
			else
				if user.password == user_params[:password]
					user.status = true
					if user.save
						flash[:notice] = '¡Welcome again, ' + user.name.capitalize
						session[:user] = user.id
						redirect_to user
					end
				else
					flash[:notice] = 'Invalid User or Password'
					render "/index"
				end
			end
		else
			flash[:notice] = 'Invalid User or Password'
			render "/index"
		end

	end

	def logout
		flash[:notice] = nil
		session[:user] = nil
		redirect_to root_path
	end

	def inactive
		user = User.find(params[:id])
		user.status = false

		if user.update(user_params)
			#flash[:notice] = 'Su cuenta ha sido desactivada'
			session[:user] = nil
			redirect_to root_path
		end
	end

	def index_archivados
		#@user = User.find(params[:id])
		@user = User.find(session[:user])
		@orders = Order.all.where(archivado: true)
	end

	def email_verification

		user = User.find(params[:id])
		#user = User.where( uuid: params[:uuid] ).first

		user.verified = true

		if user.save
		    flash[:notice] = "¡Your account has been activated!"
		    redirect_to root_path
		  else
		    flash[:notice] = "Your account cannot be activated"
		    render root_path
		end
		
	end

  def forgot_check

    time1 = Time.new
    user = User.where(email: user_params[:email]).first
    #user.forgot = time1.sec.to_s + time1.min.to_s + time1.hour.to_s + time1.day.to_s + time1.month.to_s + time1.year.to_s

    if user
      #if !user.provider_uid
        user.forgot = time1.hour.to_s + time1.day.to_s + time1.month.to_s + time1.year.to_s
        if user.save
          #url = request.protocol + request.host_with_port + "/forgot/" + user.uuid
          url = request.protocol + request.host_with_port + "/forgot/" + user.id.to_s
          #UserMailer.email_forgot(user.name, user.email, url).deliver
          UserMailer.email_forgot(user.name, user.email, url).deliver_now
          flash[:notice] = "Se te ha enviado un correo para cambiar de pass"
          redirect_to root_path
        end
      #else
        #flash[:notice] = "El correo está registrado con Facebook o Twitter"
        #render "/index"
      #end
    else
      flash[:notice] = "This Email doesn't exist"
      render "/index"
    end

  end

  def forgot_change
    time1 = Time.new
    #@user = User.where(uuid: params[:uuid]).first
    #puts "PARAMETRO="+params[:uuid]
    @user = User.find(params[:id])
    
    #actual_forgot = time1.sec.to_s + time1.min.to_s + time1.hour.to_s + time1.day.to_s + time1.month.to_s + time1.year.to_s
    actual_forgot = time1.hour.to_s + time1.day.to_s + time1.month.to_s + time1.year.to_s

    if @user.forgot == actual_forgot
      render "forgot_change"
    else
      flash[:notice] = "Errorseins, se vencio pide otra vez"
      redirect_to root_path
    end
  end 

   def forgot_success
    
    #@user = User.where(uuid: params[:uuid]).first
    @user = User.find(params[:id])
    
    puts "TAM:"+ params[:user][:password].length.to_s

    if params[:user][:password] != "" || params[:user][:password].length > 5

     #@user.password = Digest::SHA1.hexdigest(params[:user][:password])
     #params[:user][:password] = @user.password
     @user.forgot = nil

        if @user.update(user_params)
          flash[:notice] = "Ha sido cambiada tu pass"
          redirect_to root_path
        else
          flash[:notice] = "Errorseins"
          render "forgot_change"
        end
    else
      flash[:notice] = "Escribe una contraseña valida"
      render "forgot_change"
    end

  end

  def reconfirm
  	user = User.find(params[:id])
  	url = request.protocol.to_s + request.host_with_port.to_s  + "/verifica/" + user.id.to_s
	#UserMailer.email_verification(user.name, user.email, url).deliver
	UserMailer.email_verification(user.name, user.email, url).deliver_now
	redirect_to edit_user_path(user)
  end

	private
	def user_params
    	params.require(:user).permit(:uuid ,:name, :username, :gender, :address, :phone, :cellphone, :email, :password, :status, :verified, :role)	
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if session[:user] %>
	<% if User.find(session[:user]).role == 0 || @user.id == session[:user] %>

<div class="container">
<div class="show_page">

	<div class="title_new">
	</div>

<%= form_for :user, url: user_path(@user), method: :patch do |f| %>
		
		<div class="edit_page">

	        <% if @user && @user.errors.any? %>
				<div id="error_explanation">
					<h2>
						Ups! <%=pluralize(@user.errors.count, "error", "errors")%> found.
					</h2>
					<ul class="list-group">
						<% @user.errors.full_messages.each do |msg| %>
							<li class="list-group-item list-group-item-danger" ><%= msg %></li>
						<% end %>
					</ul>	
				</div>
			<% end %>

			<div class="input-group">
					<span class="input-group-addon" id="basic-addon1">  Name </span>
					<%=f.text_field :name, :class => "form-control", :required => true %>
			</div>	

  			<div class="input-group" style="margin-top:10px;">
		 		<span class="input-group-addon" id="basic-addon1">  Username </span>
		 		<%= f.text_field :username, :class => "form-control", :required => true %>
		 	</div>	

			<div class="input-group" style="margin-top:10px;">
	  			<span class="input-group-addon">
	  				<%= f.radio_button(:gender, "male")%>
	  			</span>
	  			<%= f.label :gender_male, "Male", :class => "form-control" %>
	  		</div>

			<div class="input-group" style="margin-top:10px;">
	  			<span class="input-group-addon">
	  				<%= f.radio_button(:gender, "female")%>
	  			</span>
	  			<%= f.label :gender_female, "Female", :class => "form-control" %>
	  		</div>	

		    <div class="input-group" style="margin-top:10px;">
		    	<span class="input-group-addon" id="basic-addon1">  Address </span>
				<%=f.text_field :address, :class => "form-control", :required => true %>
			</div>

			<div class="input-group" style="margin-top:10px;">
				<span class="input-group-addon" id="basic-addon1">  Telephone </span>
				<%=f.text_field :phone, :class => "form-control", :required => true %>

				<span class="input-group-addon" id="basic-addon1">  CellPhone </span>
				<%=f.text_field :cellphone, :class => "form-control", :required => true %>
			</div>

			<div class="input-group" style="margin-top:10px;">
				<span class="input-group-addon" id="basic-addon1">  Email </span>
				<%=f.email_field :email, :class => "form-control", :required => true %>
			</div>

			<div class="input-group" style="margin-top:10px;">
				<span class="input-group-addon" id="basic-addon1">  Password </span>
				<%=f.password_field :password, :class => "form-control", :required => true %>
			</div>

<!--
	<fieldset>
		<%=f.file_field :image %>
	</fieldset>
-->
		<a href="<%= user_path(@user) %>" class="btn btn-default" style="margin: 10px 0 3px 0;">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			Back
		</a>

		<button type="submit" name="commit" value="Save changes" class="btn btn-success" style="margin: 10px 0 3px 0;">
		 	<span class="glyphicon glyphicon-ok" aria-hidden="true" style="margin-right:4px;"></span>Save changes
		</button>	

<% end %>

		<%= form_for :order, url: reconfirm_path(@user), method: :post do |f| %>
		<%= f.submit 'Re-confirm pass', :class=> "btn btn-link", data:{confirm: "¿Are you sure?"} %>
		<% end %>

		<%if @user.role == 2 %>

			<%= form_for :user, url: inactive_path(@user), method: :patch do |f| %>
				<%= f.hidden_field "name" %>
				<%= f.hidden_field "username" %>
				<%= f.hidden_field "email" %>
				<%= f.hidden_field "password" %>
				
				<button type="submit" name="commit" value="Save changes" data-confirm="¿Are you sure?" class="btn btn-danger" style="margin: 0px 0 15px 0;">
		 		<span class="glyphicon glyphicon-trash" aria-hidden="true" style="margin-right:4px;"></span>Delete account
				</button>

			<% end %>
		<% end %>	


		</div>
	</div>
</div>	

	<% else %>
		<h2 class="not_found">Pagina no encontrada</h2>
	<% end %>
<% else %>
	<h2 class="not_found">Pagina no encontrada</h2>	
<% end %>


app/views/users/index_archivados.html.erb
<div class="container">
<div class="show_page">
<% if session[:user] %>

	<% if User.find(session[:user]).role < 2 %>

		<% if @orders.count > 0 %>

			<div class="title_new">
				<a href="<%= user_path(@user) %>" class="btn btn-primary">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					Volver
				</a>
			</div>
			
	<table class="table table-striped table-hover ">
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Items</th>
					<th>Address</th>
					<th>Created</th>
					<th>Delivery</th>
					<th>Expira</th>
					<th>Type</th>
					<th>Price</th>
					<th>Status</th>
					<% if @user.role == 0 %>
					<th>Pagado</th>
					<% end %>
					<th colspan = 2>Actions</th>
				</tr>

				<% @orders.each do |order| %>
					
					<tr>
						<td><%= order.id %></td>
						<% if @user.role != 2 %>
							<td><%= User.find(order.user.id).name %></td>
						<% end %>
						
						<td>

							<% for i in 0...order.cant.length %>
								<%= order.cant[i].capitalize %> <%= order.size[i] %><br>
							<% end %>
						</td>

						<td><%= order.address %></td>
						<% if @user.role == 0 %>
							<td><%= order.order_date.to_date %></td>
						<% end %>
						<td><%= order.entrega_date.asctime[0..order.entrega_date.asctime.length-9] %></td>

						<% if @user.role == 0 %>
							<td><%= order.expires_date.to_date %></td>
						<% end %>
						
						<td><%= order.tipo.capitalize[0..2] %></td>
						<td><strong><%= "$" + order.price.to_s %></strong></td>

						<% if @user.role == 0 %>
						<td><%= order.bill_status.to_s.capitalize %></td>
						<% end %>

						<td>
							<%= form_for :order, url: user_change_status_path(@user.id,order), method: :patch do |f| %>	
								<%= f.select 'status', options_for_select([["Enviado", 'send'], ["Pendiente", 'pending'],["Rechazado", 'rejected']]) %>
								<%= f.submit 'Change' %>
							<% end %>
						</td>

						<td>
							<%= link_to "Delete", user_order_path(@user.id,order), method: :delete, data:{confirm: "¿Are you sure?"} %>
						</td>

					</tr>

				<% end %>
			</table>

<% else %>
	<h3>No hay pedidos archivados</h3>
<% end %>


	<% else %>
		<h2 class="not_found">Pagina no encontrada</h2>
	<% end %>
<% else %>
	<h2 class="not_found">Pagina no encontrada</h2>	
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<% if session[:user] %>
		<% if User.find(session[:user]).role == 0 || @user.id == session[:user] %>




	<% if @orders.count > 0 %>

		<div class="show_page">

	<% if flash[:notice] %>
		<div class="alert alert-dismissible alert-success" style="margin-top:2px;">
	  		<button type="button" class="close" data-dismiss="alert">×</button>
	  		<%= flash[:notice] %>
		</div>
	<% end %>
	
		<div class="title_new">
			<% if @user.verified %>
				<a href="<%= new_user_order_path(@user) %>" class="btn btn-success">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					New order
				</a>
			<% else %>
					<a href="#" class="btn btn-danger disabled">
						First confirm your password
					</a>	
			<% end %>

			<a href="#modal" class="btn btn-primary modal_hist">
				<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
				History
			</a>
		</div>

	<% if @user.role == 2 %>
		<div class= "user_page">
			<table class="table table-striped table-hover ">
				<tr>
					<th colspan = 2>Items</th>
					<th>Price</th>
					<th>Status</th>
				</tr>

				
				<% @orders.each do |order| %>
					<tr>
						<td>
							<% for i in 0...order.cant.length %>
								<%= order.cant[i].capitalize %> <%= order.size[i] %><br>
							<% end %>
						</td>
						<td id="actions">

						<ul>
							<li>
							<a href="#modal" class="modal_det btn btn-link" onclick="showModal(['<%= order.id %>','<%= order.address %>','<%= order.tipo.capitalize %>','<%= order.entrega_date.asctime[0..order.entrega_date.asctime.length-9] %>'])" >Details</a>
							</li>




							<% if order.status == 'pending' || order.status == 'send' %> <!-- Pendiente o enviado -->
								<% if !order.bill_status %> <!-- si no ha pagado -->
									<% if @actual_date < order.expires_date %> <!-- si no ha expirado -->
										<li>
											<a href="<%= edit_user_order_path(@user.id,order) %>" class="btn btn-link"> Edit </a>
										</li>

										<li>
											<%= form_for :order, url: user_change_status_path(@user.id,order), method: :patch do |f| %>
												<%= f.submit 'Cancel', :class=> "btn btn-link", data:{confirm: "¿Are you sure?"} %>
											<% end %>
										</li>

										<li>
											<%= form_for :order, url: user_delete_order_path(@user.id,order), method: :patch do |f| %>
											<%= f.submit 'Delete', :class=> "btn btn-link", data:{confirm: "¿Are you sure?"} %>
											<% end %>
										</li>


									<% end %>
								<% end %>
								<% else %>						
									<li>
										<%= form_for :order, url: user_delete_order_path(@user.id,order), method: :patch do |f| %>
										<%= f.submit 'Delete', :class=> "btn btn-link", data:{confirm: "¿Are you sure?"} %>
										<% end %>
									</li>
							<% end %>
							</ul>
						</td>

						<div class="modal fade" id="det_modal">
						  <div class="modal-dialog">
						    <div class="modal-content">
						      <div class="modal-header">
						        <button type="button" class="close close_modal"><span aria-hidden="true">&times;</span></button>
						        <h4 class="modal-title" id="exampleModalLabel"></h4>
						      </div>
						      <div class="modal-body">
						        <form>
						          
						          <div class="form-group">
						            <label for="recipient-name" class="control-label">Address</label>
						            <p style="display:inline;" class="text-muted" id="adr"> </p>
						          </div>

						          <div class="form-group">
						            <label for="message-text" class="control-label">Type</label>
						            <p style="display:inline;" class="text-muted" id="tip"> </p>
						          </div>

						          <div class="form-group">
						            <label for="message-text" class="control-label">Delivery</label>
						            <p style="display:inline;" class="text-muted" id="ent"> </p>
						          </div>

						        </form>
						      </div>
						      <div class="modal-footer">

						        <button type="button" class="close_modal btn btn-primary">Ok</button>
						      </div>
						    </div>
						  </div>
						</div>
						
						<td><strong><%= "$" + order.price.to_s %></strong></td>

						<td>
							<% if order.status != 'rejected' %>
								<% if order.status != 'cancelled' %>
									<% if @actual_date < order.expires_date %>
										<% if !order.bill_status %>

											<%= form_tag user_payment_path(@user.id,order) do %>
											  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
											  		  data-image="/img/documentation/checkout/marketplace.png"
											          data-key="pk_test_kmiucY5Mcsr8aIBsSxK4fwl0"
											          data-name="<%= order.cant.length %> Item(s)"
										          	  data-description="<% for i in 0...order.cant.length %>
														<%= order.cant[i].capitalize %> <%= order.size[i] %>
														<% end %>"
											          data-amount="<%= (order.price * 100).to_s %>"
											          data-locale="auto">
											  </script>
											<% end %>

										<% else %>
											<%= order.status.capitalize %>
										<% end %>
									<% else %>
										Expired	
									<% end %>
								<% else %>
										Cancelled
								<% end %>
							<% else %>
									Rejected
							<% end %>	
						</td>

					</tr>
				<%end%>
			</table>
		</div>
	<% else %>

			<table class="table">
				<tr>
					<th>#</th>
					<% if @user.role != 2 %>
						<th>Name</th>
					<% end %>
					<th>Items</th>
					<th>Address</th>
					<% if @user.role == 0 %>
					<th>Created</th>
					<% end %>
					<th>Delivery</th>
					<% if @user.role == 0 %>
						<th>Expira</th>
					<% end %>
					<th>Type</th>
					<th>Price</th>
					<th>Status</th>
					<% if @user.role == 0 %>
					<th>Pagado</th>
					<% end %>

					<th>Actions</th>
				</tr>

				<% @orders.each do |order| %>
					
					<tr>
						<td><%= order.id %></td>

						<td>
							<strong><%= User.find(order.user.id).name %></strong>
						</td>
						
						<td>
							<% for i in 0...order.cant.length %>
								<%= order.cant[i].capitalize %> <%= order.size[i] %><br>
							<% end %>
						</td>

						<td><%= order.address %></td>
						<% if @user.role == 0 %>
							<td><%= order.order_date.to_date %></td>
						<% end %>
						<td><%= order.entrega_date.asctime[0..order.entrega_date.asctime.length-9] %></td>

						<% if @user.role == 0 %>
							<td><%= order.expires_date.to_date %></td>
						<% end %>
						
						<td><%= order.tipo.capitalize[0..2] %></td>
						<td><strong><%= "$" + order.price.to_s %></strong></td>

						<td>
								<% if order.status != 'cancelled' %>
									<% if order.status != 'rejected' %>
										<% if @actual_date < order.expires_date %>
											<% if !order.bill_status %>
										<!--
											<%= form_tag user_payment_path(@user.id,order) do %>
										  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
										  		  data-image="/img/documentation/checkout/marketplace.png"
										          data-key="pk_test_kmiucY5Mcsr8aIBsSxK4fwl0"
										          data-name="<%= order.cant.length %> Item(s)"
									          	  data-description="<% for i in 0...order.cant.length %>
													<%= order.cant[i].capitalize %> <%= order.size[i] %>
													<% end %>"
										          data-amount="<%= (order.price * 100).to_s %>"
										          data-locale="auto">
											  </script>
											<% end %>
											-->
												<strong style="color:red;">Sin pagar</strong>
											<% else %>
												<%= order.status.capitalize %>
											<% end %>
										<% else %>
											Expired	
										<% end %>
									<% else %>
											Cancelled
									<% end %>
								<% else %>
										Rejected
								<% end %>		
						</td>

						<% if @user.role == 0 %>
						<td><%= order.bill_status.to_s.capitalize %></td>
						<% end %>

						<% if @user.role == 2 %>

								<% if order.status != 'cancelled' %>
									<% if @actual_date < order.expires_date %>
										<% if !order.bill_status %>
											<td>
												<a href="<%= edit_user_order_path(@user.id,order) %>" class="btn btn-link"> Edit </a>

												<%= form_for :order, url: user_change_status_path(@user.id,order), method: :patch do |f| %>
													<%= f.submit 'Cancel', :class=> "btn btn-link"%>
												<% end %>

												<%= link_to "Delete", user_order_path(@user.id,order), method: :delete, data:{confirm: "¿Are you sure?"},:class=> "btn btn-link" %>
											</td>
										<% end %>
									<% end %>
								<% end %>

						<% else %>
							<td>
								<%= form_for :order, url: user_change_status_path(@user.id,order), method: :patch do |f| %>	

									<select class="form-control" name="order[status]" id="order_status" style="max-width:130px;">
										<option value="delayed">Entregado</option>
										<option value="send">Enviado</option>
										<option value="pending">Pendiente</option>
										<option value="rejected">Rechazado</option>
									</select>

									<button type="submit" name="commit" value="Change" class="btn btn-success" style="vertical-align: top;">
 									 <span class="glyphicon glyphicon-ok" aria-hidden="true" style="margin-right:4px;"></span>Change
									</button>
									
								<% end %>

								<ul class="more_opt">
									<li>
										<%= form_for :order, url: user_archivado_path(@user.id,order), method: :patch do |f| %>

											<button type="submit" name="commit" value="Archivar" class="btn btn-sm">
											<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true" style="margin-right:4px;"></span>
												Archivar
											</button>

										<% end %>
									</li>
									<li>
										<a class="btn btn-danger btn-sm" data-confirm="¿Are you sure?" rel="nofollow" data-method="delete" href="<%= user_order_path(@user.id,order) %>">
											<span class="glyphicon glyphicon-remove" aria-hidden="true" style="margin-right:4px;"></span>	
											Delete
										</a>
									</li>
								</ul>
							</td>

						<% end %>
					</tr>

				<% end %>
			</table>
			
		<% end %>

</div>
</div>
		<% else %>

			<div class="not_found">
				<h1>There aren't orders</h1>
				
				<% if @user.verified %>
					<a href="<%= new_user_order_path(@user) %>" class="btn btn-success">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
						New order
					</a>
					<% if @orders_history.count > 0 %>
						<a href="#modal" class="btn btn-primary modal_hist">
							<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
							History
						</a>
					<% end %>
				<% else %>
					<a href="#" class="btn btn-danger disabled">
						First confirm your password
					</a>
				<% end %>

			</div>

		<% end %>

		<% else %>
			<h2 class="not_found">Pagina no encontrada</h2>
		<% end %>
	<% else %>
		<h2 class="not_found">Pagina no encontrada</h2>	
	<% end %>



	<!-- Modal History -->
  <div class="modal fade" id="history_modal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal">&times;</button>
          	<h4 class="modal-title"><strong>Purchase history</strong></h4>
        </div>
        <div class="modal-body">

        	<table class="table">
        		<tr>
        			<% if @user.role < 2 %>
        				<th>Name</th>
        			<% end %>
        			<th>Order</th>
        			<th>Created at</th>
        		</tr>

	        	<% @orders_history.each do |order| %>
	        		<tr>
        				<% if @user.role < 2 %>
        					<td> <strong><%= User.find(order.user.id).name %></strong> </td>
        				<% end %>
						<td>
							<ul>
							<% for i in 0...order.cant.length %>
								<li><%= order.cant[i].capitalize %> <%= order.size[i] %></li>
							<% end %>
							</ul>
						</td>
						<td>
							<%= order.entrega_date.asctime[0..order.entrega_date.asctime.length-9] %>
						</td>
	        		</tr>
	        	<% end %>
        	</table>

        </div>
        <div class="modal-footer">
          <button type="button" class="close_modal btn btn-primary">Ok</button>
        </div>
      </div>
  	</div>
  </div>