config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :users

  resources :users do
    post "/contact" => "users#contact", as: "contact"
    resources :orders
    resources :msgs
    patch "/orders/:id/archivado" => "orders#archivado", as: "archivado"
    patch "/orders/:id/change_status" => "orders#change_status", as: "change_status"
    patch "/orders/:id/delete" => "orders#delete", as: "delete_order"
    post "/orders/:id/payment" => "orders#payment", as: "payment"
    post "/orders/calcula" => "orders#calcula", as: "calcula"
  end

  get "/logout" => "users#logout", as: "logout"
  post "/login" => "users#login", as: "login"
  patch "/users/:id/inactive" => "users#inactive", as: "inactive"
  

  post "/users/:id/reconfirm" => "users#reconfirm", as: "reconfirm"

  get "/users/:id/index_archivados" => 'users#index_archivados', as: "index_archivados"

  get "verifica/:id", to: "users#email_verification", as: "confirmemail"

  post "/forgot" => "users#forgot_check", as: "forgot_check"
  get "forgot/:id" => "users#forgot_change", as: "forgot_change"
  patch "/forgot/:id/success" => "users#forgot_success", as: "forgot_success"

  

end

app/models/order.rb
class Order < ActiveRecord::Base

	#validates :cant, :size, :address, :tipo, presence: true, on: :create
	
	validates :cant, :address, :tipo, presence: true

	#validates :address, presence: true
	belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	#skip_before_action :verify_authenticity_token

	def index
		@orders = Order.all
		@user = User.find(session[:user])
      	
      	respond_to do |format|
        	format.html
        	format.json {render json: @orders if @user.role == 0}
      	end
	end

	def new
		@user = User.find(params[:user_id])
	end

	def create
		

		@user = User.find(params[:user_id])
		@order = Order.new(order_params)
		@order.archivado = false

		if params[:order][:cant] && params[:order][:size]
			if params[:order][:cant].split(",").length == params[:order][:size].split(",").length

				@order.bill_status = false
				@order.cant = params[:order][:cant].split(",")
				@order.size = params[:order][:size].split(",")

				@order.price = 0

				for i in 0...@order.cant.length
					@order.price += Price.where(name: @order.cant[i]).where(size: @order.size[i]).first.value
				end

				@order.user_id = params[:user_id]
				@order.status = 'pending'
				@order.order_date = Time.now
				@order.expires_date = Time.now + 1.day
				@order.entrega_date = Time.now + 1.hour

				if @order.save
					redirect_to user_path(params[:user_id])
				else
					render 'new'
				end
			else
				flash[:notice] = 'NO HIJO'
				render 'new'
			end
		else
			render 'new'
		end

	end

	def calcula
		puts "valor: "+	params[:valor].to_s
	end

	def show
		@order = Order.find(params[:id])

		#@user = User.find(session[:user])
		#render "index"
	end

	def edit
		@user = User.find(params[:user_id])
		@order = Order.find(params[:id])
	end

	def update
		@order = Order.find(params[:id])


		if params[:order][:cant] && params[:order][:size]
			
			@order.cant = params[:order][:cant].split(",")
			@order.size = params[:order][:size].split(",")
			params[:order][:cant] = params[:order][:cant].split(",")
			params[:order][:size] = params[:order][:cant].split(",")

			if @order.update(order_params)
				redirect_to user_order_path(params[:user_id],@order)
			else
				render "edit"
			end
		else
			render "edit"
		end		
	end

	def destroy
		order = Order.find(params[:id])
		order.destroy
		redirect_to user_path(params[:user_id])
	end


	def change_status
		@user = User.find(session[:user])
		@order = Order.find(params[:id])

		if @user.role == 2
			@order.status = 'cancelled'
		else
			@order.status = order_params[:status]
		end

	    if @order.save
	      redirect_to user_path(@user)
	    end
	end

	def delete
		@user = User.find(session[:user])
		@order = Order.find(params[:id])

		if @user.role == 2
			@order.status = 'deleted'
		else
			@order.status = order_params[:status]
		end

	    if @order.save
	      redirect_to user_path(@user)
	    end
	end	

	def archivado
		@user = User.find(session[:user])
		@order = Order.find(params[:id])
		@order.archivado = true

		puts "USER_ORDER: " + params[:user_id] + params[:id]

	    if @order.save
	      redirect_to user_path(@user)
	    end
	end


	def new_payment
		@order=Order.find(params[:order_id])
	end

	def payment

		user=User.find(params[:user_id])
		@order=Order.find(params[:id])

		@amount = @order.price * 100
		Stripe.api_key = 'sk_test_tHKvI69La7NqUvVyhzKTvlRo'
		token = params[:stripeToken]
		# Create the charge on Stripe's servers - this will charge the user's card

		begin

		  charge = Stripe::Charge.create(
		    :amount => @amount, # amount in cents, again
		    :currency => "usd",
		    :source => token,
		    :description => "Example charge"
		  )

			@order.bill_status = true
			if @order.save
				redirect_to user_path(params[:user_id])
			else
				render user_path(params[:user_id])
			end

		rescue Stripe::CardError => e
		  # The card has been declined
			@order.bill_status = false
			if @order.save
				redirect_to user_path(params[:user_id])
			else
				render user_path(params[:user_id])
			end
		end

	end	
	

	private
	def order_params
		params.require(:order).permit(:user_id ,:cant, :size, :order_date, :expires_date, :entrega_date, :address, :status, :tipo, :archivado, :token, :price, :bill_status)	
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<div class="container">

<% if session[:user] %>
	<% if User.find(session[:user]).role == 0 || @user.id == session[:user] %>
<div class="show_page">

	<div class="title_new">
		<%= form_for :order, url: user_order_path(@user.id,@order), method: :patch do |f| %>
			<% if @order && @order.errors.any? %>
				<div id="error_explanation">
					<h2>
						Ups! <%=pluralize(@order.errors.count, "error", "errors")%> found.
					</h2>
					<ul class="list-group">
						<% @order.errors.full_messages.each do |msg| %>
							<li class="list-group-item list-group-item-danger" ><%= msg %></li>
						<% end %>
					</ul>	
				</div>
			<% end %>
			<h1>Select what you want<br>(Max. 10 items)</h1>
		</div>

			<div id='field_div' style="margin:15px;"></div>
			
			<div class='add_rem' style="margin:15px;">
				<div id='add' class="btn btn-primary btn-sm" >
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					Add
				</div>
				<div id='rem'class="btn btn-danger btn-sm" >
					<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
					Remove
				</div>
			</div>

			<!--
			<div id='editB'></div>
			<div id='saveB'></div>
			-->

			<%=f.text_field :cant, :id => "prods_bd_field", :hidden => "true" %>
			<%=f.text_field :size, :id => "tams_bd_field", :hidden => "true" %> 
			<%=f.text_field :price, :hidden => "true" %> 

 			<div class="input-group" style="margin:15px;">
		 		<span class="input-group-addon" id="basic-addon1">Address</span>
		 		<%= f.text_field :address, :value => @user.address, :class => "form-control", :required => true %>
	 		</div>

		 	<div class="input-group" style="margin:15px;">
		 		<span class="input-group-addon" id="basic-addon1">Type</span>
		 		<select name="order[tipo]" id="order_tipo" class="form-control">
		 			<option value="domicilio">Domicilio</option>
					<option value="recoger">Recoger</option>
				</select>
			</div>



			

			<div class="alert alert-dismissible alert-warning" style="margin: 0px;">
 				<h3 id="label_price" style="margin: 0 0 10px 0;">Total: $0</h3>

				<a href="<%= user_path(@user) %>" class="btn btn-default" >
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					Back
				</a>

				<button type="submit" name="commit" value="Change" class="btn btn-success" style="">
				 <span class="glyphicon glyphicon-ok" aria-hidden="true" style="margin-right:4px;"></span>Finish
				</button>
			</div>

	<% end %>


</div>
</div>

	<% else %>
		<h2 class="not_found">Pagina no encontrada</h2>
	<% end %>
<% else %>
	<h2 class="not_found">Pagina no encontrada</h2>	
<% end %>

app/views/orders/index.html.erb
<% if session[:user] %>
	<% if @user.role == 0 %>
	
		<% if @orders.count > 0 %>

		<h3>Pedidos</h3>

		<table>
			<tr>
				<th>#</th>
				<% if @user.role != 2 %>
					<th>Nombre</th>
				<% end %>
				<th>Cantidad</th>
				<th>Tamaño</th>
				<th>Dirección</th>
				<th>Creación</th>
				<th>Entrega</th>
				<th>Expira</th>
				<th>Tipo</th>
				<th>Status</th>
				<th colspan= 3>Actions</th>
			</tr>

			<% @orders.each do |order| %>
				
				<tr>
					<td><%= order.id %></td>
					<% if @user.role != 2 %>
						<td><%= User.find(order.user.id).name %></td>
					<% end %>
					<td><%= order.cant %></td>
					<td><%= order.size %></td>
					<td><%= order.address %></td>
					<td><%= order.order_date.to_date %></td>
					<td><%= order.entrega_date.to_date %></td>
					<td><%= order.expires_date.to_date %></td>
					<td><%= order.tipo.capitalize %></td>
					<td><%= order.status.capitalize %></td>

					<% if @user.role == 2 %>
						<% if order.status == 'pending' %>
							<td>
								<a href="<%= edit_user_order_path(@user.id,order) %>"> Editar </a>
							</td>

							<td>
								<%= form_for :order, url: change_status_path(order), method: :patch do |f| %>
									<%= f.submit 'Cancel' %>
								<% end %>
							</td>

							<td>
								<%= link_to "Delete", user_order_path(@user.id,order), method: :delete, data:{confirm: "¿Are you sure?"} %>
							</td>

						<% end %>
					<% else %>
						<td>
							<%= form_for :order, url: user_change_status_path(@user.id,order), method: :patch do |f| %>	
								<%= f.select 'status', options_for_select([["Enviado", 'send'], ["Pendiente", 'pending'],["Rechazado", 'rejected']]) %>
								<%= f.submit 'Change' %>
							<% end %>
						</td>

						<td>
							<%= form_for :order, url: user_archivado_path(@user.id,order), method: :patch do |f| %>
								<%= f.submit 'Archivar' %>
							<% end %>
						</td>

					<% end %>				


				</tr>

			<% end %>
		</table>

		<% else %>
			<h3>No hay pedidos</h3>
		<% end %>


	<% else %>
		<h2 class="not_found">Pagina no encontrada</h2>
	<% end %>

<% else %>
	<h2 class="not_found">Pagina no encontrada</h2>
<% end %>

app/views/orders/new.html.erb
<div class="container">

<% if session[:user] %>
	<% if User.find(session[:user]).role == 0 || @user.id == session[:user] %>
<div class="show_page">

	<div class="title_new">
		<h1>Select what you want<br>(Max. 10 items)</h1>
		<%= form_for :order, url: user_orders_path do |f| %>
			<% if @order && @order.errors.any? %>
				<div id="error_explanation">
					<h2>
						<strong>Ups! <%=pluralize(@order.errors.count, "error", "errors")%> found.</strong>
					</h2>
					<ul class="list-group">
						<% @order.errors.full_messages.each do |msg| %>
							<li class="list-group-item list-group-item-danger" ><%= msg %></li>
						<% end %>
					</ul>	
				</div>
			<% end %>
		</div>

			<div id='field_div' style="margin:15px;"></div>
			
			<div class='add_rem' style="margin:15px;">
				<div id='add' class="btn btn-primary btn-sm" >
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					Add
				</div>
				<div id='rem'class="btn btn-danger btn-sm" >
					<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
					Remove
				</div>
			</div>

			<!--
			<div id='editB'></div>
			<div id='saveB'></div>
			-->

			<%=f.text_field :cant, :id => "prods_bd_field", :hidden => "true" %>
			<%=f.text_field :size, :id => "tams_bd_field", :hidden => "true" %> 
			<%=f.text_field :price, :hidden => "true" %> 

 			<div class="input-group" style="margin:15px;">
		 		<span class="input-group-addon" id="basic-addon1">Address</span>
		 		<%= f.text_field :address, :value => @user.address, :class => "form-control", :required => true %>
	 		</div>

		 	<div class="input-group" style="margin:15px;">
		 		<span class="input-group-addon" id="basic-addon1">Type</span>
		 		<select name="order[tipo]" id="order_tipo" class="form-control">
		 			<option value="domicilio">Domicilio</option>
					<option value="recoger">Recoger</option>
				</select>
			</div>



			

			<div class="alert alert-dismissible alert-warning" style="margin: 0px;">
 				<h3 id="label_price" style="margin: 0 0 10px 0;">Total: $0</h3>

				<a href="<%= user_path(@user) %>" class="btn btn-default" >
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					Back
				</a>

				<button type="submit" name="commit" value="Change" class="btn btn-success" style="">
				 <span class="glyphicon glyphicon-ok" aria-hidden="true" style="margin-right:4px;"></span>Finish
				</button>
			</div>

	<% end %>


</div>
</div>

	<% else %>
		<h2 class="not_found">Pagina no encontrada</h2>
	<% end %>
<% else %>
	<h2 class="not_found">Pagina no encontrada</h2>	
<% end %>

app/views/orders/show.html.erb
<% if session[:user] %>
	<% if User.find(session[:user]).role < 2 || @user.id == session[:user] %>

		<h2>Order No <%= @order.id %></h2>

		Cantidad <%= @order.cant %><br>
		Tamaño <%= @order.size %><br>
		Creación <%= @order.order_date %><br>
		Expira el <%= @order.expires_date %><br>
		Status <%= @order.status %><br>
		Entregado el <%= @order.entrega_date %><br>
		Pertenece al user #<%= @order.user_id %>


	<% else %>
		<h2 class="not_found">Pagina no encontrada</h2>
	<% end %>
<% else %>
	<h2 class="not_found">Pagina no encontrada</h2>	
<% end %>