config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :users

  resources :users do
    post "/contact" => "users#contact", as: "contact"
    resources :orders
    resources :msgs
    patch "/orders/:id/archivado" => "orders#archivado", as: "archivado"
    patch "/orders/:id/change_status" => "orders#change_status", as: "change_status"
    patch "/orders/:id/delete" => "orders#delete", as: "delete_order"
    post "/orders/:id/payment" => "orders#payment", as: "payment"
    post "/orders/calcula" => "orders#calcula", as: "calcula"
  end

  get "/logout" => "users#logout", as: "logout"
  post "/login" => "users#login", as: "login"
  patch "/users/:id/inactive" => "users#inactive", as: "inactive"
  

  post "/users/:id/reconfirm" => "users#reconfirm", as: "reconfirm"

  get "/users/:id/index_archivados" => 'users#index_archivados', as: "index_archivados"

  get "verifica/:id", to: "users#email_verification", as: "confirmemail"

  post "/forgot" => "users#forgot_check", as: "forgot_check"
  get "forgot/:id" => "users#forgot_change", as: "forgot_change"
  patch "/forgot/:id/success" => "users#forgot_success", as: "forgot_success"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LuzMA</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="banner">
	<div class="subbanner">

		<% if session[:user] %>
			<h1 class="ruta">LuzMA</h1>
		<% else  %>	
			<h1 class="ruta">Lechonas LuzMA</h1>
		<% end %>

		<ul class="desk_options">
		<% if session[:user] %>
			
				<li>
					<% if @user.role == 0 %>
						<p id="admin">Admin</p>
					<% elsif @user.role == 1 %>
						<p id="venta">Seller</p>
					<% else %>
						<% if @user.verified %>
							<p id="user_yes">User</p>
						<% else %>
							<p id="user_no">User</p>
						<% end %>	
					<% end %>
				</li>
					
				<% if !@user.verified %>
					<li>
						<p id="no_confirm">Email not verified</p>
					</li>
				<% end %>
				
				<li>
					<p>Hello, <strong><%=@user.name.capitalize %></strong></p>
				</li>

				<li><a href="/">Home</a></li>

				<% if @user.role == 0 %>
					<li>
						<a href="<%= users_path %>">Users</a>
					</li>
					<!--
					<li>
						<a href="<%= user_orders_path(@user) %>">Orders</a>
					</li>
					-->
				<% end %>

				<li>
					<a href="<%= edit_user_path(@user) %>">Profile</a>
				</li>

				<li>
					<a href="#modal" class="modal_cont">Contact</a>
				</li>

				<li>
					<a href="<%= logout_path %>">Logout</a>
				</li>
			<% else %>
				<li>
					<a href="#modal" class="modal_log">Login</a>
				</li>
				<li>
					<a href="#modal" class="modal_sig">Sign Up</a>
				</li>
			<% end %>
		</ul>

		<ul class="mob_options" >
			<% if session[:user] %>
			
				<li>
					<% if @user.role == 0 %>
						<p id="admin">Admin</p>
					<% elsif @user.role == 1 %>
						<p id="venta">Seller</p>
					<% else %>
						<% if @user.verified %>
							<p id="user_yes">User</p>
						<% else %>
							<p id="user_no">User</p>
						<% end %>	
					<% end %>
				</li>
				
				<li>
					<p><strong><%=@user.name.capitalize %></strong></p>
				</li>

				<li id="mod" href="#modal_opcs" class="modal_director">
						<a id="volver">
							<span style="width: 28px;" class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span> 
						</a>
				</li>

			<% else %>

				<li id="mod" href="#modal_opcs" class="modal_director">
					<a id="volver">
						<span style="width: 28px;" class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span> 
					</a>
				</li>

			<% end %>
		</ul>

	</div>
</div>

  <!-- Modal Login -->
  <div class="modal fade" id="login_modal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><strong>Login</strong></h4>
        </div>
        <div class="modal-body">
          
          <h5 style="margin-bottom:30px;">Please type below your credentials</h5>


	  		<%= form_for :user, url: login_path do |f| %>
	  			<div class="input-group">
			 		<span class="input-group-addon" id="basic-addon1">  Username </span>
			 		<%= f.text_field :username, :class => "form-control", :required => true %>
			 	</div>	

			 	<div class="input-group" style="margin-top:20px;">
					<span class="input-group-addon" id="basic-addon1">  Password </span>
					<%= f.password_field :password, :class => "form-control", :required => true %>
				</div>	

        </div>
        <div class="modal-footer">
		  <a href="#modal" class="modal_forg" style="margin-right:20px;">¿Forgot Pass?</a>
          <button type="button" class="close_modal btn btn-default">Cancel</button>
          <button type="submit" class="btn btn-success">Go</button>
        </div>
        <% end %>
      </div>
      
    </div>
  </div>

 
   <!-- Modal Forgot-->
  <div class="modal fade" id="forgot_modal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><strong>Password Recovery</strong></h4>
        </div>
        <div class="modal-body">


        <% if flash[:notice] %>
			<div class="alert alert-dismissible alert-danger">
	 			<button type="button" class="close" data-dismiss="alert">×</button>
				<%= flash[:notice] %>
			</div>
		<% end %>

        <h5 style="margin-bottom:30px;">Please type below the <strong>Email</strong> with are you signed</h5>

		<%= form_for :user, url: forgot_check_path do |f| %>
				<div class="input-group">
					<span class="input-group-addon" id="basic-addon1">  Email </span>
					<%= f.email_field :email, :class => "form-control", :required => true %>
				</div>

        </div>
        <div class="modal-footer">
          <button type="button" class="close_modal btn btn-default">Cancel</button>
          <button type="submit" class="btn btn-primary">Send</button>
        </div>
        <% end %>
      </div>
      
    </div>
  </div> 


<!-- Modal SignUp -->
  <div class="modal fade" id="sign_modal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal">&times;</button>
          	<h4 class="modal-title"><strong>Create Account</strong></h4>
        </div>
        <div class="modal-body">
        
		<%= form_for :user, url: users_path do |f| %>
		
	        <% if @user && @user.errors.any? %>
				<div id="error_explanation">
					<h2>
						There are <%=pluralize(@user.errors.count, "error", "errors")%>
					</h2>
					<ul class="list-group">
						<% @user.errors.full_messages.each do |msg| %>
							<li class="list-group-item list-group-item-danger" ><%= msg %></li>
						<% end %>
					</ul>	
				</div>
			<% end %>

				<div class="input-group">
					<span class="input-group-addon" id="basic-addon1">  Name </span>
					<%=f.text_field :name, :class => "form-control", :required => true %>
				</div>	

	  			<div class="input-group" style="margin-top:10px;">
			 		<span class="input-group-addon" id="basic-addon1">  Username </span>
			 		<%= f.text_field :username, :class => "form-control", :required => true %>
			 	</div>	

				<div class="input-group" style="margin-top:10px;">
		  			<span class="input-group-addon">
		  				<%= f.radio_button(:gender, "male")%>
		  			</span>
		  			<%= f.label :gender_male, "Male", :class => "form-control" %>
		  		</div>

				<div class="input-group" style="margin-top:10px;">
		  			<span class="input-group-addon">
		  				<%= f.radio_button(:gender, "female")%>
		  			</span>
		  			<%= f.label :gender_female, "Female", :class => "form-control" %>
		  		</div>	

			    <div class="input-group" style="margin-top:10px;">
			    	<span class="input-group-addon" id="basic-addon1">  Address </span>
					<%=f.text_field :address, :class => "form-control", :required => true %>
				</div>

				<div class="input-group" style="margin-top:10px;">
					<span class="input-group-addon" id="basic-addon1">  Telephone </span>
					<%=f.text_field :phone, :class => "form-control", :required => true %>

					<span class="input-group-addon" id="basic-addon1">  CellPhone </span>
					<%=f.text_field :cellphone, :class => "form-control", :required => true %>
				</div>

				<div class="input-group" style="margin-top:10px;">
					<span class="input-group-addon" id="basic-addon1">  Email </span>
					<%=f.email_field :email, :class => "form-control", :required => true %>
				</div>

				<div class="input-group" style="margin-top:10px;">
					<span class="input-group-addon" id="basic-addon1">  Password </span>
					<%=f.password_field :password, :class => "form-control", :required => true %>
				</div>
		<!--
			<fieldset>
				<%=f.file_field :image %>
			</fieldset>
		-->

        </div>
        <div class="modal-footer">
          <button type="button" class="close_modal btn btn-default">Cancel</button>
          <button type="submit" class="btn btn-success">Create Account</button>
        </div>
        <% end %>
      </div>
      
    </div>
  </div>


<% if session[:user] %>
<!-- Modal Contacto -->
  <div class="modal fade" id="contact_modal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal">&times;</button>
          	<h4 class="modal-title"><strong>Contact With Us</strong></h4>
        </div>
        <div class="modal-body">
        
		<%= form_for :msg, url: user_msgs_path(@user) do |f| %>
		
	        <% if @msg && @msg.errors.any? %>
				<div id="error_explanation">
					<h2>
						There are <%=pluralize(@msg.errors.count, "error", "errors")%>
					</h2>
					<ul class="list-group">
						<% @msg.errors.full_messages.each do |msg| %>
							<li class="list-group-item list-group-item-danger" ><%= msg %></li>
						<% end %>
					</ul>	
				</div>
			<% end %>


				 <div class="form-group">

      				<label>
      						<span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> (126) 3445 <br>
      						<span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> (324) 324-3244 <br>
      						<span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> +34 (534) 5435
      				</label>
      				
      			</div>	

				<div class="input-group" style="margin-top:10px;">
					<span class="input-group-addon" id="basic-addon1">  Email </span>
					<%=f.email_field :email, :class => "form-control", :required => true, :value => @user.email %>
				</div>

				<div class="input-group" style="margin-top:10px;">
					<span class="input-group-addon" id="basic-addon1">  Subject </span>
					<%=f.text_field :subject, :class => "form-control", :required => true %>
				</div>

			    <div class="input-group" style="margin-top:10px;">
			    	<span class="input-group-addon" id="basic-addon1">  Message </span>
					<%=f.text_area :message, :class => "form-control", :required => true %>
				</div>

        </div>
        <div class="modal-footer">
          <button type="button" class="close_modal btn btn-default">Cancel</button>
          <button type="submit" class="btn btn-success">Send</button>
        </div>
        <% end %>
      </div>
      
    </div>
  </div>
<% end %> 

  <div hidden class="modal_actor" id="modal_opcs">
	<div class="modal_content">

		<ul class="list-group">

			<% if session[:user] %>

				<% if !@user.verified %>
					<li  class="list-group-item"><p id="no_confirm">Email not verified</p></li>
				<% end %>

				<li  class="list-group-item"><a href="/">Home</a></li>

				<% if @user.role == 0 %>
					<li  class="list-group-item">
						<a href="<%= users_path %>">Users</a>
					</li>
					<li  class="list-group-item">
						<a href="<%= user_orders_path(@user) %>">Orders</a>
					</li>
				<% end %>

				<li  class="list-group-item">
					<a href="<%= edit_user_path(@user) %>">Profile</a>
				</li>
				<li  class="list-group-item">
					<a href="<%= logout_path %>">Logout</a>
				</li>

			<% else %>
				
				<li  class="list-group-item">
					<a href="#modal" class="modal_log">Login</a>
				</li>
				<li  class="list-group-item">
					<a href="#modal" class="modal_sig">Sign Up</a>
				</li>

			<% end %>

		</ul>
	</div>
</div>

<% if flash[:notice] %>
	<div class="alert alert-dismissible alert-danger" style="margin-top:80px;position:fixed;width:100%;">
 		<button type="button" class="close" data-dismiss="alert">×</button>
		<%= flash[:notice] %>
	</div>
<% end %>

<%= yield %>

</body>
</html>